name: colors_of_clothes
description: Project to detect colors of clothes

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: 0.10.5
  tflite:
    path: D:/_work/colors_of_clothes/tflite/flutter_tflite-master/flutter_tflite-master
  get_it: 7.2.0
  native_device_orientation: 1.1.4
  image: 4.0.17
  palette_generator: 0.3.3+2
  flutter_bloc: 8.1.2
  bloc_concurrency: 0.2.1
  photo_manager: 2.6.0
  sliver_tools: 0.2.10
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  injectable: 2.1.1
  animate_gradient: 0.0.2
  rxdart: 0.27.7


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  injectable_generator: 2.1.5
  flutter_native_splash: 2.2.19

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true



  assets:
    - assets/labels.txt
    - assets/model_unquant.tflite

  fonts:
    - family: ColorsOfClothesCustomIcons
      fonts:
        - asset: assets/icons/ColorsOfClothesCustomIcons.ttf

flutter_native_splash:
  color: "#FBFCFD"
  image: assets/images/icon.png
  color_dark: "#191C1D"

  android_12:
    image: assets/images/icon.png
    icon_background_color: "#FBFCFD"
    icon_background_color_dark: "#191C1D"